<?php namespace Modules\Notification\Commands;

use Illuminate\Console\Command;

class CreateNotification extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'notifications:create {moduleName} {name} {--via=*}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a notification for zgldh/scaffold';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        // Move template to module folder
    }

    private function getViaOptions()
    {
        $via = $this->option('via') ?: ['database', 'mail'];
        return $via;
    }

    /**
     * Get the destination class path.
     *
     * @param  string $name
     * @return string
     */
    protected function getPath($name)
    {
        $name = Str::replaceFirst($this->rootNamespace(), '', $name);

        return $this->laravel['path'] . '/' . str_replace('\\', '/', $name) . '.php';
    }

    protected function getDefaultNamespace($rootNamespace)
    {
        return parent::getDefaultNamespace($rootNamespace); // TODO: Change the autogenerated stub
    }
}
